<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Hair Mists</name>
   <tag></tag>
   <elementGuidId>3ee4a749-d051-4d5a-ba0e-d3471ebe5b4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div/div[4]/div/a[6]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>3034aa58-4fa2-4dd9-8862-e328cbacdfbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hair Mists</value>
      <webElementGuid>119daee9-a9c3-4f94-b2c1-373040831264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;header__container&quot;]/div[@class=&quot;header&quot;]/div[@class=&quot;styles_megaMenu__Niti_&quot;]/div[@class=&quot;styles_mainMegaMenu___v0_9&quot;]/a[@class=&quot;styles_megaMenuItem__v14fq false&quot;]/p[1]</value>
      <webElementGuid>88fafa57-31ba-4b2f-bc45-171ec7a057bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div[4]/div/a[6]/p</value>
      <webElementGuid>589c1386-1e62-4ff4-9299-ce1658460064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send Feedback'])[3]/following::p[6]</value>
      <webElementGuid>69a27be4-c10a-4e4a-8fe5-df782ca33744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Us'])[3]/following::p[6]</value>
      <webElementGuid>00ffcad3-803f-4c4f-8a38-6c9e78fd3eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Best Sellers'])[2]/preceding::p[1]</value>
      <webElementGuid>16a5588e-f24a-4888-85d6-87521160a759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]/p</value>
      <webElementGuid>daca3bc3-308b-4802-a71b-46226bdfd09b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Hair Mists' or . = 'Hair Mists')]</value>
      <webElementGuid>4cdbb48e-4307-4879-80ad-82ebbf560131</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
