<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_HM_1_image</name>
   <tag></tag>
   <elementGuidId>265eb711-3eeb-425c-8415-4a903fb6de4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.styles_imageContainer__Qxdx1 > span > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/div[2]/div[2]/div[4]/div/div/div/div/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b197560c-792a-4f7a-8d77-681437452687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Fbackend.new-theme.snaptec.co%2Fmedia%2Fcatalog%2Fproduct%2Fcache%2Fd3470a8a7a3ceb0328c354c4622cde6a%2F0%2F3%2F0301020487-3.jpg&amp;w=640&amp;q=75</value>
      <webElementGuid>b4aad5ab-55b0-456f-ab7d-8b538be17d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>1d8c2f8b-bf61-4565-813a-5bf3c81936de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>intrinsic</value>
      <webElementGuid>a2aef056-2475-422f-9a4d-8d077bec253b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Fbackend.new-theme.snaptec.co%2Fmedia%2Fcatalog%2Fproduct%2Fcache%2Fd3470a8a7a3ceb0328c354c4622cde6a%2F0%2F3%2F0301020487-3.jpg&amp;w=256&amp;q=75 1x, /_next/image?url=https%3A%2F%2Fbackend.new-theme.snaptec.co%2Fmedia%2Fcatalog%2Fproduct%2Fcache%2Fd3470a8a7a3ceb0328c354c4622cde6a%2F0%2F3%2F0301020487-3.jpg&amp;w=640&amp;q=75 2x</value>
      <webElementGuid>0489af21-35ed-4569-8a39-d0a71ece9821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_main___hWF4&quot;]/div[@class=&quot;main-page&quot;]/div[@class=&quot;content-container&quot;]/div[@class=&quot;infinite-scroll-component__outerdiv&quot;]/div[@class=&quot;infinite-scroll-component&quot;]/div[@class=&quot;product-list-container&quot;]/div[@class=&quot;styles_productCard__qAttO&quot;]/div[@class=&quot;styles_imageContainer__Qxdx1&quot;]/span[1]/img[1]</value>
      <webElementGuid>a17a2909-ea42-461c-8cf4-a27522861e73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/div[2]/div[2]/div[4]/div/div/div/div/span/img</value>
      <webElementGuid>b4427635-1bce-49f7-b1cc-85d0f711d01b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/span/img</value>
      <webElementGuid>8a711ade-cc93-41f4-bc6b-a095875ff640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_next/image?url=https%3A%2F%2Fbackend.new-theme.snaptec.co%2Fmedia%2Fcatalog%2Fproduct%2Fcache%2Fd3470a8a7a3ceb0328c354c4622cde6a%2F0%2F3%2F0301020487-3.jpg&amp;w=640&amp;q=75']</value>
      <webElementGuid>8ab6069c-a407-47aa-a2ef-0755510e484f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
