<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SS_1_image</name>
   <tag></tag>
   <elementGuidId>0c9fa81d-18bf-48b7-a78b-b60045ad0283</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.styles_imageContainer__Qxdx1 > span > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/div[2]/div[2]/div[4]/div/div/div/div/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6fee1fa4-1529-419a-ab10-210987b10ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Fbackend.new-theme.snaptec.co%2Fmedia%2Fcatalog%2Fproduct%2Fcache%2Fd3470a8a7a3ceb0328c354c4622cde6a%2Fm%2Fu%2Fmusk.jpg&amp;w=640&amp;q=75</value>
      <webElementGuid>126efb58-b958-464a-a234-8b24a7d10e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>2ea62c6b-9ffd-4caa-bdf4-48f4f80cbb15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>intrinsic</value>
      <webElementGuid>4d3f0d16-321a-4edc-a917-69ed1b02b1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Fbackend.new-theme.snaptec.co%2Fmedia%2Fcatalog%2Fproduct%2Fcache%2Fd3470a8a7a3ceb0328c354c4622cde6a%2Fm%2Fu%2Fmusk.jpg&amp;w=256&amp;q=75 1x, /_next/image?url=https%3A%2F%2Fbackend.new-theme.snaptec.co%2Fmedia%2Fcatalog%2Fproduct%2Fcache%2Fd3470a8a7a3ceb0328c354c4622cde6a%2Fm%2Fu%2Fmusk.jpg&amp;w=640&amp;q=75 2x</value>
      <webElementGuid>1ee0b237-85a0-4f33-9ea5-9844b6705c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_main___hWF4&quot;]/div[@class=&quot;main-page&quot;]/div[@class=&quot;content-container&quot;]/div[@class=&quot;infinite-scroll-component__outerdiv&quot;]/div[@class=&quot;infinite-scroll-component&quot;]/div[@class=&quot;product-list-container&quot;]/div[@class=&quot;styles_productCard__qAttO&quot;]/div[@class=&quot;styles_imageContainer__Qxdx1&quot;]/span[1]/img[1]</value>
      <webElementGuid>3e6e4e87-d21f-425b-b2e4-dcb2bbe2afe3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/div[2]/div[2]/div[4]/div/div/div/div/span/img</value>
      <webElementGuid>668738c9-f081-4ed7-b566-0911ea5cb4de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/span/img</value>
      <webElementGuid>07ec171a-66a8-4678-9879-4087fc6d567f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_next/image?url=https%3A%2F%2Fbackend.new-theme.snaptec.co%2Fmedia%2Fcatalog%2Fproduct%2Fcache%2Fd3470a8a7a3ceb0328c354c4622cde6a%2Fm%2Fu%2Fmusk.jpg&amp;w=640&amp;q=75']</value>
      <webElementGuid>490c5550-c1de-4080-beec-96ec3456318a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
