<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SS_5_Image</name>
   <tag></tag>
   <elementGuidId>0674998b-64f6-4d30-b838-fad64332f342</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/div[2]/div[2]/div[4]/div/div/div[5]/div/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>01db64c8-f5a7-41a3-bb85-39098a1bd20a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Fbackend.new-theme.snaptec.co%2Fmedia%2Fcatalog%2Fproduct%2Fcache%2Fd3470a8a7a3ceb0328c354c4622cde6a%2Ff%2Fi%2Ffile_14.jpg&amp;w=640&amp;q=75</value>
      <webElementGuid>03e3a422-b1b9-40c4-a0f9-8a53709fd936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>dcddef3b-526b-4d44-ad9b-e092c1132e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>intrinsic</value>
      <webElementGuid>3b94dec0-fd05-45c6-8017-e00bc0de3299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Fbackend.new-theme.snaptec.co%2Fmedia%2Fcatalog%2Fproduct%2Fcache%2Fd3470a8a7a3ceb0328c354c4622cde6a%2Ff%2Fi%2Ffile_14.jpg&amp;w=256&amp;q=75 1x, /_next/image?url=https%3A%2F%2Fbackend.new-theme.snaptec.co%2Fmedia%2Fcatalog%2Fproduct%2Fcache%2Fd3470a8a7a3ceb0328c354c4622cde6a%2Ff%2Fi%2Ffile_14.jpg&amp;w=640&amp;q=75 2x</value>
      <webElementGuid>ddbd1934-0372-4247-a134-b74de5958769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_main___hWF4&quot;]/div[@class=&quot;main-page&quot;]/div[@class=&quot;content-container&quot;]/div[@class=&quot;infinite-scroll-component__outerdiv&quot;]/div[@class=&quot;infinite-scroll-component&quot;]/div[@class=&quot;product-list-container&quot;]/div[@class=&quot;styles_productCard__qAttO&quot;]/div[@class=&quot;styles_imageContainer__Qxdx1&quot;]/span[1]/img[1]</value>
      <webElementGuid>92e9cf05-9784-44ea-be6d-25343f065298</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/div[2]/div[2]/div[4]/div/div/div[5]/div/span/img</value>
      <webElementGuid>28eceadf-4fbd-4be3-9243-0cfac5b89a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/span/img</value>
      <webElementGuid>02d39d32-e4a3-4cbf-bd53-02adb80f8e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_next/image?url=https%3A%2F%2Fbackend.new-theme.snaptec.co%2Fmedia%2Fcatalog%2Fproduct%2Fcache%2Fd3470a8a7a3ceb0328c354c4622cde6a%2Ff%2Fi%2Ffile_14.jpg&amp;w=640&amp;q=75']</value>
      <webElementGuid>8184e492-f833-4165-ada6-c6e7d176e06d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
