<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SS_main_banner</name>
   <tag></tag>
   <elementGuidId>478f3517-a2c8-4085-8f45-ec2a86ffb784</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.styles_categoryBanner__Fzz9u > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/div[2]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9052da1c-b0c1-4b52-9e0c-11fe4597ed07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://backend.new-theme.snaptec.co/media/catalog/category/category-headers/stanizer-category.jpg</value>
      <webElementGuid>a7b4b617-fda5-4969-911e-502bbb079342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_main___hWF4&quot;]/div[@class=&quot;main-page&quot;]/div[@class=&quot;styles_categoryBanner__Fzz9u&quot;]/img[1]</value>
      <webElementGuid>96e9e693-9d4c-481d-9302-3d3fa7c13f5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/div[2]/div/img</value>
      <webElementGuid>5e76aaf3-2226-45ac-817a-fc7a9a7dff48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://backend.new-theme.snaptec.co/media/catalog/category/category-headers/stanizer-category.jpg')]</value>
      <webElementGuid>d0a500e7-a693-49bf-9ab1-1130717eec35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>f8f97f20-48c6-412d-a779-fe4b5e44a3be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://backend.new-theme.snaptec.co/media/catalog/category/category-headers/stanizer-category.jpg']</value>
      <webElementGuid>653366d0-a0f1-4170-9bef-5c85f286be77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
