<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SS_4_image</name>
   <tag></tag>
   <elementGuidId>e6001c80-cb48-4aa8-8808-ce10a38d637e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/div[2]/div[2]/div[4]/div/div/div[4]/div/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>95856580-091b-4450-88ee-029764695718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Fbackend.new-theme.snaptec.co%2Fmedia%2Fcatalog%2Fproduct%2Fcache%2Fd3470a8a7a3ceb0328c354c4622cde6a%2Fc%2Fe%2Fcentro.jpg&amp;w=640&amp;q=75</value>
      <webElementGuid>2c4ad8a2-b747-4d27-a5bb-788bb55424c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>8e3f9bc8-2235-45ef-8512-9b593f9d9694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>intrinsic</value>
      <webElementGuid>3b0762f3-b7bf-49b7-bff8-232b4c3796a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Fbackend.new-theme.snaptec.co%2Fmedia%2Fcatalog%2Fproduct%2Fcache%2Fd3470a8a7a3ceb0328c354c4622cde6a%2Fc%2Fe%2Fcentro.jpg&amp;w=256&amp;q=75 1x, /_next/image?url=https%3A%2F%2Fbackend.new-theme.snaptec.co%2Fmedia%2Fcatalog%2Fproduct%2Fcache%2Fd3470a8a7a3ceb0328c354c4622cde6a%2Fc%2Fe%2Fcentro.jpg&amp;w=640&amp;q=75 2x</value>
      <webElementGuid>c3fa7d10-c1b3-4885-8796-74b5686f284e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_main___hWF4&quot;]/div[@class=&quot;main-page&quot;]/div[@class=&quot;content-container&quot;]/div[@class=&quot;infinite-scroll-component__outerdiv&quot;]/div[@class=&quot;infinite-scroll-component&quot;]/div[@class=&quot;product-list-container&quot;]/div[@class=&quot;styles_productCard__qAttO&quot;]/div[@class=&quot;styles_imageContainer__Qxdx1&quot;]/span[1]/img[1]</value>
      <webElementGuid>1cf6420e-2fce-4c6d-8ffe-89e0618e7ffc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/div[2]/div[2]/div[4]/div/div/div[4]/div/span/img</value>
      <webElementGuid>4d898dd8-1079-4fe0-b1d5-95d4d4593b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span/img</value>
      <webElementGuid>dfd03592-df6a-442d-86ef-5cbfec3171ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_next/image?url=https%3A%2F%2Fbackend.new-theme.snaptec.co%2Fmedia%2Fcatalog%2Fproduct%2Fcache%2Fd3470a8a7a3ceb0328c354c4622cde6a%2Fc%2Fe%2Fcentro.jpg&amp;w=640&amp;q=75']</value>
      <webElementGuid>34c2015d-596f-49bc-bd07-7afd4d79e619</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
