<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_BS_5_image</name>
   <tag></tag>
   <elementGuidId>84750c0c-116b-45d7-b9a3-686a3b0b7aa1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/div[2]/div[2]/div[4]/div/div/div[8]/div/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>67239014-bfd0-488c-94a5-251e193fa451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Fbackend.new-theme.snaptec.co%2Fmedia%2Fcatalog%2Fproduct%2Fcache%2Fd3470a8a7a3ceb0328c354c4622cde6a%2Fb%2Fe%2Fbella_3.png&amp;w=640&amp;q=75</value>
      <webElementGuid>806036d0-b253-4ca8-976a-5a4074598b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>7372d633-35fd-4b77-ad40-5353b26db149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>intrinsic</value>
      <webElementGuid>c3659a0c-232b-45fa-accc-1c241f25f346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Fbackend.new-theme.snaptec.co%2Fmedia%2Fcatalog%2Fproduct%2Fcache%2Fd3470a8a7a3ceb0328c354c4622cde6a%2Fb%2Fe%2Fbella_3.png&amp;w=256&amp;q=75 1x, /_next/image?url=https%3A%2F%2Fbackend.new-theme.snaptec.co%2Fmedia%2Fcatalog%2Fproduct%2Fcache%2Fd3470a8a7a3ceb0328c354c4622cde6a%2Fb%2Fe%2Fbella_3.png&amp;w=640&amp;q=75 2x</value>
      <webElementGuid>1e8424b6-2b51-415d-a8f3-14498da6f8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_main___hWF4&quot;]/div[@class=&quot;main-page&quot;]/div[@class=&quot;content-container&quot;]/div[@class=&quot;infinite-scroll-component__outerdiv&quot;]/div[@class=&quot;infinite-scroll-component&quot;]/div[@class=&quot;product-list-container&quot;]/div[@class=&quot;styles_productCard__qAttO&quot;]/div[@class=&quot;styles_imageContainer__Qxdx1&quot;]/span[1]/img[1]</value>
      <webElementGuid>2b0a73e4-e0f0-4efd-842d-c55f3e45e27c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//*[@id=&quot;__next&quot;]/div[3]/div[2]/div[2]/div[4]/div/div/div[8]/div[1]/span/img</value>
      <webElementGuid>44e4281c-2560-426f-9ba2-e652889b5e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/span/img</value>
      <webElementGuid>4ea8e67a-e8a9-4bdf-80df-a8cf011a541e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_next/image?url=https%3A%2F%2Fbackend.new-theme.snaptec.co%2Fmedia%2Fcatalog%2Fproduct%2Fcache%2Fd3470a8a7a3ceb0328c354c4622cde6a%2Fb%2Fe%2Fbella_3.png&amp;w=640&amp;q=75']</value>
      <webElementGuid>185ddfea-f0d0-41a7-b100-ca87f03d2099</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
