<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_BS_3_image</name>
   <tag></tag>
   <elementGuidId>f2a2d22e-b450-4d80-b009-403b9aadff19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/div[2]/div[2]/div[4]/div/div/div[3]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3aa9feb6-3ad8-411f-b39c-8ff35508d3b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://backend.new-theme.snaptec.co/media/catalog/product/cache/d3470a8a7a3ceb0328c354c4622cde6a/0/2/02_4.jpg</value>
      <webElementGuid>87d42b71-3cb8-428d-9de4-45df9f484378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>5f539ba6-cfc6-4434-a2f7-ff7b2c525ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_main___hWF4&quot;]/div[@class=&quot;main-page&quot;]/div[@class=&quot;content-container&quot;]/div[@class=&quot;infinite-scroll-component__outerdiv&quot;]/div[@class=&quot;infinite-scroll-component&quot;]/div[@class=&quot;product-list-container&quot;]/div[@class=&quot;styles_productCard__qAttO&quot;]/div[@class=&quot;styles_imageContainer__Qxdx1&quot;]/img[@class=&quot;img-fluid&quot;]</value>
      <webElementGuid>fd7565c1-ac9a-46e5-82fb-2159b2b620e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/div[2]/div[2]/div[4]/div/div/div[3]/div/img</value>
      <webElementGuid>1647f0c0-3711-494b-a758-89ae8859e334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://backend.new-theme.snaptec.co/media/catalog/product/cache/d3470a8a7a3ceb0328c354c4622cde6a/0/2/02_4.jpg')]</value>
      <webElementGuid>39705458-f46a-4114-9339-1f6631eff94f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[3]/div/img</value>
      <webElementGuid>3c34597a-2090-49b9-86db-7a2ff034d40e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://backend.new-theme.snaptec.co/media/catalog/product/cache/d3470a8a7a3ceb0328c354c4622cde6a/0/2/02_4.jpg']</value>
      <webElementGuid>6120ebec-4617-42f9-80ed-4444604852e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
