<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_bestSeller_1</name>
   <tag></tag>
   <elementGuidId>b637771d-472a-41cb-80ec-7074adfecbd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.styles_imageContainer__Qxdx1 > img.img-fluid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/div[2]/div[2]/div[4]/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c966d149-e86f-40f3-8a1e-ca7f11b9546d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://backend.new-theme.snaptec.co/media/catalog/product/cache/d3470a8a7a3ceb0328c354c4622cde6a/a/r/arabian_leather_5_.jpg</value>
      <webElementGuid>9a11c8df-9fd6-4ab1-a482-54dd4cf9fbea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>06bb5a90-fcef-4033-9422-ce266f83f593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_main___hWF4&quot;]/div[@class=&quot;main-page&quot;]/div[@class=&quot;content-container&quot;]/div[@class=&quot;infinite-scroll-component__outerdiv&quot;]/div[@class=&quot;infinite-scroll-component&quot;]/div[@class=&quot;product-list-container&quot;]/div[@class=&quot;styles_productCard__qAttO&quot;]/div[@class=&quot;styles_imageContainer__Qxdx1&quot;]/img[@class=&quot;img-fluid&quot;]</value>
      <webElementGuid>d4bcec43-6860-45c7-8c6f-7e143896d9d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/div[2]/div[2]/div[4]/div/div/div/div/img</value>
      <webElementGuid>9ebb4ae6-765e-443c-95eb-8c7a64436b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://backend.new-theme.snaptec.co/media/catalog/product/cache/d3470a8a7a3ceb0328c354c4622cde6a/a/r/arabian_leather_5_.jpg')]</value>
      <webElementGuid>3d02c914-1ff1-488a-a911-b88b6c0c0126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/img</value>
      <webElementGuid>dbce7877-db33-4926-9c98-ed6fe866f6a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://backend.new-theme.snaptec.co/media/catalog/product/cache/d3470a8a7a3ceb0328c354c4622cde6a/a/r/arabian_leather_5_.jpg']</value>
      <webElementGuid>f37e4121-c30d-4496-a2bb-84f7723a1195</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
