<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_BS_4_image</name>
   <tag></tag>
   <elementGuidId>2179b6c0-ad83-406b-8b2d-ac6008aa1209</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/div[2]/div[2]/div[4]/div/div/div[4]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b152900d-2b06-42a4-86c3-858cd203c17f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://backend.new-theme.snaptec.co/media/catalog/product/cache/d3470a8a7a3ceb0328c354c4622cde6a/_/3/_3__3.jpg</value>
      <webElementGuid>a95cd4f2-33b8-4dd8-bf47-12dd056f81ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>ab75efb2-2d56-46cf-8943-a9dd70e57912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_main___hWF4&quot;]/div[@class=&quot;main-page&quot;]/div[@class=&quot;content-container&quot;]/div[@class=&quot;infinite-scroll-component__outerdiv&quot;]/div[@class=&quot;infinite-scroll-component&quot;]/div[@class=&quot;product-list-container&quot;]/div[@class=&quot;styles_productCard__qAttO&quot;]/div[@class=&quot;styles_imageContainer__Qxdx1&quot;]/img[@class=&quot;img-fluid&quot;]</value>
      <webElementGuid>9bef6c2e-a42a-438a-8476-d0cc5cb82d94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/div[2]/div[2]/div[4]/div/div/div[4]/div/img</value>
      <webElementGuid>eeefc788-6323-4c0d-9bba-982824874af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://backend.new-theme.snaptec.co/media/catalog/product/cache/d3470a8a7a3ceb0328c354c4622cde6a/_/3/_3__3.jpg')]</value>
      <webElementGuid>71c29e6e-4d8d-4033-b561-0b954115ec1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/img</value>
      <webElementGuid>3800a6b4-ff12-4877-921b-778ffa1e2d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://backend.new-theme.snaptec.co/media/catalog/product/cache/d3470a8a7a3ceb0328c354c4622cde6a/_/3/_3__3.jpg']</value>
      <webElementGuid>27264c4a-a418-41f3-bee7-ec2d4477f952</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
