<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_product 1 Image</name>
   <tag></tag>
   <elementGuidId>43422f36-62b6-495e-83b7-535b24e6d180</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/div[2]/div[2]/div[4]/div/div/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.styles_imageContainer__Qxdx1 > img.img-fluid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2f456dce-0142-4449-9924-e28e269740a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://backend.new-theme.snaptec.co/media/catalog/product/cache/d3470a8a7a3ceb0328c354c4622cde6a/a/r/arabian_leather_5_.jpg</value>
      <webElementGuid>21d06d6a-e323-43ff-92c8-8707649d4196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>e2c7ebf9-91f4-44b8-923c-35e5c15d2210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_main___hWF4&quot;]/div[@class=&quot;main-page&quot;]/div[@class=&quot;content-container&quot;]/div[@class=&quot;infinite-scroll-component__outerdiv&quot;]/div[@class=&quot;infinite-scroll-component&quot;]/div[@class=&quot;product-list-container&quot;]/div[@class=&quot;styles_productCard__qAttO&quot;]/div[@class=&quot;styles_imageContainer__Qxdx1&quot;]/img[@class=&quot;img-fluid&quot;]</value>
      <webElementGuid>248dc244-bb65-4aa0-9eb6-7e160af768d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/div[2]/div[2]/div[4]/div/div/div/div[2]/img</value>
      <webElementGuid>53d9f958-abad-4ce5-a7f0-17d2ec323a76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://backend.new-theme.snaptec.co/media/catalog/product/cache/d3470a8a7a3ceb0328c354c4622cde6a/a/r/arabian_leather_5_.jpg')]</value>
      <webElementGuid>ba49954c-fdc2-44f0-8888-f13f5c1a5d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/img</value>
      <webElementGuid>620b5128-e3fc-4eb8-b869-9bd8f1a751e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://backend.new-theme.snaptec.co/media/catalog/product/cache/d3470a8a7a3ceb0328c354c4622cde6a/a/r/arabian_leather_5_.jpg']</value>
      <webElementGuid>ba7bd133-5d26-49d3-bfa9-91dee14f891c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
